# 이 파일은 배포 시, CodeDeploy가 참조하는 파일이다.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/wakuwaku

    # 아래 두 줄의 코드는 같은 디렉토리가 있을 때, 덮어쓰기를 하기 위함
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/wakuwaku/
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu