spring:
  application:
    name: WakuWaku
  profiles:
    active: API-KEY,dev
    group:
      prod: API-KEY

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'

  mvc:
    static-path-pattern: /static/**

server:
  servlet:
    session:
      tracking-modes: cookie



