openapi: 3.0.1
info:
  title: WakuWaku API Document
  description: WakuWaku API 명세서입니다.
  version: 0.1.0
servers:
- url: http://localhost:8080
  description: local server
- url: http://15.164.249.106:8080
  description: Develop server
tags: []
paths: {}
components:
  schemas: {}
