openapi: 3.0.1
info:
  title: WakuWaku API Document
  description: WakuWaku API 명세서입니다.
  version: 0.1.0
servers:
- url: http://localhost:8080
  description: local server
- url: http://15.164.249.106:8080
  description: Develop server
tags: []
paths:
  /oauth/{oauthServerType}:
    get:
      tags:
      - OAuth
      summary: OAuth Authorization Code 요청 URL로 리디렉션 (인증 코드 요청)
      description: OAuth Authorization Code 요청 URL로 리디렉션 (인증 코드 요청)
      operationId: redirect-auth-code-request-url
      parameters:
      - name: oauthServerType
        in: path
        description: "OAuth 서버 타입: NAVER, KAKAO, GOOGLE"
        required: true
        schema:
          type: string
      responses:
        "302":
          description: "302"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/oauth-oauthServerType486549215'
              examples:
                redirect-auth-code-request-url:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\"}"
  /oauth/login/{oauthServerType}:
    get:
      tags:
      - OAuth
      summary: OAuth 로그인.
      description: OAuth 로그인.
      operationId: oauth-login
      parameters:
      - name: oauthServerType
        in: path
        description: "OAuth 서버 타입: NAVER, KAKAO, GOOGLE"
        required: true
        schema:
          type: string
      - name: code
        in: query
        description: 인증 코드
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/wakuwaku-v1-members-id242545501'
              examples:
                oauth-login:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\",\"data\":{\"\
                    id\":1}}"
  /wakuwaku/v1/restaurant:
    get:
      tags:
      - Get Simple Info
      summary: Get Simple Info By Search Word
      description: "응답(data[]의 size) 개수가 최대 20개까지 가능함."
      operationId: get simple info
      parameters:
      - name: search
        in: query
        description: 검색어 (장소명 혹은 지역명만 입력)
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/wakuwaku-v1-restaurant1414997480'
              examples:
                get simple info:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\",\"data\":[{\"\
                    placeId\":\"ChIJAQCl79GMGGARZheneHqgIUs\",\"name\":\"우동신\",\"\
                    rating\":4.1,\"userRatingsTotal\":3965,\"location\":{\"latitude\"\
                    :35.686489,\"longitude\":139.697001},\"photoUrl\":[\"https://lh3.googleusercontent.com/places/ANXAkqG2xQHKla3ebHNhRNrgMFi4WB6hGbR6LZTd2ig0PK5qTwkIvk0EP1fzPQ8UXmAt3FcU1Gz0XjYYCQJvFJQQVhAMss2GtKenoAI=s4800-w1440-h810\"\
                    ]}]}"
  /wakuwaku/v1/members/list:
    get:
      tags:
      - Member
      summary: 회원 목록을 조회합니다.
      description: 회원 목록을 조회합니다.
      operationId: get-member-list
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/wakuwaku-v1-members-list1387809491'
              examples:
                get-member-list:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\",\"data\":[{\"\
                    email\":\"test@example.com\",\"oauthServerId\":\"oauth-id\",\"\
                    oauthServerType\":\"GOOGLE\",\"birthday\":\"1990-01-01\",\"profileImageUrl\"\
                    :\"http://example.com/profile.jpg\",\"nickname\":\"nickname\"\
                    ,\"role\":\"USER\"}]}"
  /wakuwaku/v1/members/{id}:
    get:
      tags:
      - Member
      summary: 회원 ID로 회원 정보를 조회합니다.
      description: 회원 ID로 회원 정보를 조회합니다.
      operationId: get-member-by-id
      parameters:
      - name: id
        in: path
        description: 회원 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/wakuwaku-v1-members-id-489354416'
              examples:
                get-member-by-id:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\",\"data\":{\"\
                    email\":\"test@example.com\",\"oauthServerId\":\"oauth-id\",\"\
                    oauthServerType\":\"GOOGLE\",\"birthday\":\"1990-01-01\",\"profileImageUrl\"\
                    :\"http://example.com/profile.jpg\",\"nickname\":\"nickname\"\
                    ,\"role\":\"USER\"}}"
    put:
      tags:
      - Member
      summary: 회원 정보를 업데이트합니다.
      description: 회원 정보를 업데이트합니다.
      operationId: update-member
      parameters:
      - name: id
        in: path
        description: 회원 ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/wakuwaku-v1-members-id653228855'
            examples:
              update-member:
                value: "{ \"nickname\": \"newNickname\", \"profileImageUrl\": \"http://example.com/new-profile.jpg\"\
                  , \"birthday\": \"1991-01-01\" }"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/wakuwaku-v1-members-id242545501'
              examples:
                update-member:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\",\"data\":{\"\
                    id\":1}}"
    delete:
      tags:
      - Member
      summary: 회원 정보를 삭제합니다.
      description: 회원 정보를 삭제합니다.
      operationId: delete-member
      parameters:
      - name: id
        in: path
        description: 회원 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/oauth-oauthServerType486549215'
              examples:
                delete-member:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\"}"
  /wakuwaku/v1/restaurant/{placeId}/details:
    get:
      tags:
      - Get Details Info
      summary: Get Details Info By PlaceId
      description: Get Details Info By PlaceId
      operationId: get details info
      parameters:
      - name: placeId
        in: path
        description: Details Info를 얻고 싶은 식당의 Place Id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/wakuwaku-v1-restaurant-placeId-details-1068373660'
              examples:
                get details info:
                  value: "{\"code\":1000,\"message\":\"요청에 성공하였습니다.\",\"data\":{\"\
                    name\":\"우동신\",\"editorialSummary\":\"다양한 반주와 함께 바삭한 튀김과 수제 우동\
                    을 맛 볼 수 있는 아담한 식당입니다.\",\"photos\":[\"https://lh3.googleusercontent.com/places/ANXAkqG2xQHKla3ebHNhRNrgMFi4WB6hGbR6LZTd2ig0PK5qTwkIvk0EP1fzPQ8UXmAt3FcU1Gz0XjYYCQJvFJQQVhAMss2GtKenoAI=s4800-w1440-h810\"\
                    ],\"dineIn\":true,\"delivery\":false,\"takeout\":false,\"website\"\
                    :\"http://www.udonshin.com/\",\"formattedPhoneNumber\":null,\"\
                    formattedAddress\":\"일본 〒151-0053 Tokyo, Shibuya City, Yoyogi,\
                    \ 2-chōme−20−１６ 相馬ビル １F\",\"reservable\":true,\"servesBreakfast\"\
                    :false,\"servesLunch\":true,\"servesDinner\":true,\"servesBeer\"\
                    :true,\"servesWine\":false,\"servesVegetarianFood\":false,\"userRatingsTotal\"\
                    :3965,\"rating\":4.1,\"reviews\":[{\"relativePublishTimeDescription\"\
                    :\"3주 전\",\"rating\":3.0,\"text\":\"붓카게 우동과 자루소바 주문\\\\n직원 매우\
                    \ 친절함.의외로 튀김 맛있다\\\\n우동 자체는 꽤 맛있긴 하지만 이게 3시간을 기다릴 맛인가?이 가격 값을\
                    \ 하는가? 하면 별점 3점인 맛\\\\n웨이팅이 아예 없고 근처에 있다면 갈만한 집이긴 한데 절대 기다려서 먹\
                    을 맛 아님!!!!\\\\n면발이 탱글하다는데 개인적으로 오사카에서 먹은 다른 우동 집이 오백만배 탱글하고 맛있\
                    었음\\\\n손님도 로컬 거의 없고 대부분 외국인임\\\\n우연히 내가 그 근처를 지나가고 있는데 웨이팅이 없다\
                    ? 할 때만 가십쇼\",\"authorName\":\"촉촉한볼따구\",\"authorProfileUrl\":\"\
                    https://lh3.googleusercontent.com/a-/ALV-UjVoB_ILlpMn32pQwKbd5R99vuCX8mSb5T4rUzTRBBRts8CQolD9=s128-c0x00000000-cc-rp-mo\"\
                    }],\"openNow\":true,\"weekdayText\":[\"월요일:오전11:00~오후10:00,화요일\
                    :오전11:00~오후10:00,수요일:오전11:00~오후10:00,목요일:오전11:00~오후10:00,금요일:오\
                    전11:00~오후10:00,토요일:오전11:00~오후10:00,일요일:오전11:00~오후10:00\"]}}"
components:
  schemas:
    wakuwaku-v1-restaurant-placeId-details-1068373660:
      type: object
      properties:
        code:
          type: number
          description: 응답 시 반환되는 code 값
        data:
          type: object
          properties:
            formattedPhoneNumber:
              type: string
              description: 식당 전화번호
            delivery:
              type: boolean
              description: 배달 가능 여부
            website:
              type: string
              description: 해당 식당의 웹 사이트 주소
            servesBeer:
              type: boolean
              description: 맥주 판매 여부
            reservable:
              type: boolean
              description: 예약 가능 여부
            rating:
              type: number
              description: 식당 별점
            userRatingsTotal:
              type: number
              description: 식당의 총 리뷰 수
            servesBreakfast:
              type: boolean
              description: 아침 식사 가능 여부
            takeout:
              type: boolean
              description: 포장 가능 여부
            photos:
              type: array
              description: 식당 사진 (최대 10개)
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            servesVegetarianFood:
              type: boolean
              description: 채식주의자를 위한 메뉴 유무
            reviews:
              type: array
              items:
                type: object
                properties:
                  authorName:
                    type: string
                    description: 리뷰 작성자 이름
                  rating:
                    type: number
                    description: 리뷰 작성자의 별점
                  relativePublishTimeDescription:
                    type: string
                    description: 현 시간으로부터 식당 리뷰 작성한 날짜
                  text:
                    type: string
                    description: 리뷰 내용
                  authorProfileUrl:
                    type: string
                    description: 리뷰 작성자의 프로필 사진 URL
            servesLunch:
              type: boolean
              description: 점심 식사 가능 여부
            formattedAddress:
              type: string
              description: 식당 주소
            servesWine:
              type: boolean
              description: 와인 판매 여부
            openNow:
              type: boolean
              description: 검색한 시점에서의 식당 오픈 여부
            name:
              type: string
              description: 식당 이름
            weekdayText:
              type: array
              description: 요일 별 식당 운영 시간
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            servesDinner:
              type: boolean
              description: 저녁 식사 가능 여부
            editorialSummary:
              type: string
              description: 식당에 대한 간단한 소개글
            dineIn:
              type: boolean
              description: 매장 내 식사 가능 여부
        message:
          type: string
          description: 응답 시 반환되는 메시지
    wakuwaku-v1-members-id-489354416:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          type: object
          properties:
            birthday:
              type: string
              description: 회원 생일
            oauthServerId:
              type: string
              description: OAuth 서버 ID
            role:
              type: string
              description: 회원 역할
            oauthServerType:
              type: string
              description: OAuth 서버 타입
            nickname:
              type: string
              description: 회원 닉네임
            profileImageUrl:
              type: string
              description: 회원 프로필 이미지 URL
            email:
              type: string
              description: 회원 이메일
        message:
          type: string
          description: 응답 메시지
    wakuwaku-v1-members-id653228855:
      type: object
      properties:
        birthday:
          type: string
          description: 새로운 생일
        nickname:
          type: string
          description: 새로운 닉네임
        profileImageUrl:
          type: string
          description: 새로운 프로필 이미지 URL
    wakuwaku-v1-members-id242545501:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          type: object
          properties:
            id:
              type: number
              description: 회원 ID
        message:
          type: string
          description: 응답 메시지
    wakuwaku-v1-members-list1387809491:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          type: array
          items:
            type: object
            properties:
              birthday:
                type: string
                description: 회원 생일
              oauthServerId:
                type: string
                description: OAuth 서버 ID
              role:
                type: string
                description: 회원 역할
              oauthServerType:
                type: string
                description: OAuth 서버 타입
              nickname:
                type: string
                description: 회원 닉네임
              profileImageUrl:
                type: string
                description: 회원 프로필 이미지 URL
              email:
                type: string
                description: 회원 이메일
        message:
          type: string
          description: 응답 메시지
    oauth-oauthServerType486549215:
      type: object
    wakuwaku-v1-restaurant1414997480:
      type: object
      properties:
        code:
          type: number
          description: 응답 시 반환되는 code 값
        data:
          type: array
          items:
            type: object
            properties:
              photoUrl:
                type: array
                description: 식당 대표 사진 URL
                items:
                  oneOf:
                  - type: object
                  - type: boolean
                  - type: string
                  - type: number
              rating:
                type: number
                description: 식당 별점
              name:
                type: string
                description: 식당 이름
              placeId:
                type: string
                description: Details Info 에 활용할 식당의 Place Id
              userRatingsTotal:
                type: number
                description: 식당 총 리뷰 수
              location:
                type: object
                properties:
                  latitude:
                    type: number
                    description: 위도
                  longitude:
                    type: number
                    description: 경도
        message:
          type: string
          description: 응답 시 반환되는 메시지
